export const API_ROUTES = {
  AUTH: {
    LOGIN: "/auth/login",
  },
  EMPRESA: {
    ADD_EMPRESA: "/empresas",
    GET_EMPRESAS: "/empresas",
    GET_EMPRESA_BY_ID: "/empresas",
    UPDATE_EMPRESA: "/empresas",
    DELETE_EMPRESA: "/empresas",
  },
  BOARD: {
    ADD_BOARD: "/boards",
    GET_BOARDS: "/boards",
    GET_BOARDS_BY_EMPRESA: "/boards/empresa/",
    GET_BOARD_BY_ID: "/boards",
    UPDATE_BOARD: "/boards",
    DELETE_BOARD: "/boards",
  },
  PEDIDO: {
    ADD_PEDIDO: "/pedidos",
    GET_PEDIDOS: "/pedidos",
    GET_PEDIDOS_BY_EMPRESA: "/pedidos/empresa/",
    GET_PEDIDO_BY_ID: "/pedidos",
    UPDATE_PEDIDO: "/pedidos",
    DELETE_PEDIDO: "/pedidos",
    MOVER_PEDIDO: "/pedidos/mover",
  },
  PEDIDO_STATUS: {
    ADD_PEDIDO_STATUS: "/pedidostatus",
    GET_PEDIDO_STATUS: "/pedidostatus",
    GET_PEDIDO_STATUS_BY_ID: "/pedidostatus",
    UPDATE_PEDIDO_STATUS: "/pedidostatus",
    DELETE_PEDIDO_STATUS: "/pedidostatus",
    GET_PEDIDO_STATUS_BY_BOARD: "/pedidostatus/board",
    GET_PEDIDO_STATUS_WITH_PEDIDOS: "/pedidostatus/pedidos/:boardId",
    GET_PEDIDO_STATUS_WITH_PEDIDOS_AND_ITENS:
      "/pedidostatus/pedidos/itens/:boardId",
  },
  PRODUTO: {
    ADD_PRODUTO: "/produtos",
    GET_PRODUTOS: "/produtos",
    GET_PRODUTOS_BY_EMPRESA_AUTH: "/produtos/empresa",
    GET_PRODUTOS_BY_EMPRESA: "/produtos/empresa/:empresaId",
    GET_PRODUTO_BY_ID: "/produtos",
    UPDATE_PRODUTO: "/produtos",
    DELETE_PRODUTO: "/produtos",
  },
  PEDIDO_ITEM: {
    ADD_PEDIDO_ITEM: "/pedidoitens",
    GET_PEDIDO_ITENS: "/pedidoitens",
    GET_PEDIDO_ITEM_BY_ID: "/pedidoitens",
    UPDATE_PEDIDO_ITEM: "/pedidoitens",
    DELETE_PEDIDO_ITEM: "/pedidoitens",
  },
  ENDERECO: {
    ADD_ENDERECO: "/enderecos",
    GET_ENDERECOS: "/enderecos",
    GET_ENDERECO_BY_ID: "/enderecos",
    UPDATE_ENDERECO: "/enderecos",
    DELETE_ENDERECO: "/enderecos",
  },
  FORMA_PAGAMENTO: {
    ADD_FORMA_PAGAMENTO: "/formapagamentos",
    GET_FORMAS_PAGAMENTO: "/formapagamentos",
    GET_FORMAS_PAGAMENTO_BY_EMPRESA: "/formapagamentos/empresa",
    GET_FORMA_PAGAMENTO_BY_ID: "/formapagamentos",
    UPDATE_FORMA_PAGAMENTO: "/formapagamentos",
    DELETE_FORMA_PAGAMENTO: "/formapagamentos",
  },
  FONTE_PEDIDO: {
    ADD_FONTE_PEDIDO: "/fontepedidos",
    GET_FONTES_PEDIDO: "/fontepedidos",
    GET_FONTE_PEDIDO_BY_ID: "/fontepedidos",
    UPDATE_FONTE_PEDIDO: "/fontepedidos",
    DELETE_FONTE_PEDIDO: "/fontepedidos",
  },
  CONFIGURACAO_EMPRESA: {
    GET_CONFIGURACAO: "/configuracao-empresa",
    CREATE_CONFIGURACAO: "/configuracao-empresa",
    UPDATE_CONFIGURACAO: "/configuracao-empresa",
    DELETE_CONFIGURACAO: "/configuracao-empresa",
  },
};
